# 列表转ndarray

In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)  # [1, 2, 3, 4]
print(type(list1))

oneArray = np.array(list1)
print(type(oneArray))  #类型是ndarray
print(oneArray)  # [1 2 3 4]

[1, 2, 3, 4]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


# ndarray与Python原生list运算效率对比,创建一维数组

In [2]:
import random
import time
import numpy as np

#随机1亿个数据
a = []
for i in range(10 ** 8):
    a.append(random.random())
print('随机完毕')

b = np.array(a)  # 转换为ndarray
print('转换完毕')

#ndarray的计算效率优于python的list
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

随机完毕
转换完毕
0.455127477645874 0.05490994453430176


In [3]:
print(type(range(10)))  # range返回的是一个range对象<class 'range'>
t2 = np.array(range(10))
print(t2)  # [0 1 2 3 4 5 6 7 8 9]
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
t3 = np.arange(0, 10, 2)  # 等价于range(0,10,2),返回ndarray
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


# 二维列表转ndarray

In [5]:
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
"""
[[1 2]
 [3 4]
 [5 6]]
"""
print(list2)  #列表的输出是有逗号的，ndarray的输出是没有逗号的      [[1, 2], [3, 4], [5, 6]]

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [6]:
print(twoArray.tolist())  # ndarray转换为列表

[[1, 2], [3, 4], [5, 6]]


# 4.3常用属性

In [7]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)

# 数据类型
print(twoArray.dtype)  # int64

2
(3, 2)
6
int64


# 4.4 调整数组的形状

In [19]:
four = np.array([[1, 2, 3], [4, 5, 6]])
print(four)

four1 = four
print(id(four))

[[1 2 3]
 [4 5 6]]
1354497489584


In [20]:
# four.shape = (3, 2)  # 改变形状，从两行三列到三行两列 deprecated
four = four.reshape((3,2), copy=False)
print(id(four))
print(id(four1))
print(four)

1354497490352
1354497489584
[[1 2]
 [3 4]
 [5 6]]


In [32]:
# 将多维变成一维数组
five = four.reshape((6,), order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开

six = four.flatten()  # 展开成一维数组
print(five)
print('-' * 50)
print(six)

five.reshape(3,2)

[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# 拓展：数组的形状
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')  # shape(24,)
print(t.ndim)  # 1维

# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)  # (4, 6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [28]:
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))  # “两个三行四列的矩阵”
print(t2)
print(t2.shape)
print(t2.ndim)  # 3

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [29]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


# 4.5 数组转换为列表

In [30]:
a = np.array([9, 12, 88, 14, 25])
print(type(a))
print(a)

list_a = a.tolist()
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[ 9 12 88 14 25]
[9, 12, 88, 14, 25]
<class 'list'>


# 5 NumPy的数据类型

In [19]:
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize)  # 1 np.int16(一个字节)
# 获取数据类型
print(f.dtype)

1
int8


In [20]:
f[4] = f[4] + 1  # 溢出
f[4]  # np.int8(-128)

C:\Users\q1209\AppData\Local\Temp\ipykernel_11800\1143178101.py:1: RuntimeWarning: overflow encountered in scalar add
  f[4] = f[4] + 1  # 溢出


np.int8(-128)

In [21]:
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)  # 显示字节数 8
print('-' * 50)

int64
8
--------------------------------------------------


In [22]:
random.random()  # 随机生成0-1之间的小数

0.9536144003953714

In [23]:
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(), 2))

# np.float16 半精度
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)  # 8
print(arr.dtype)  # float64

# 取小数点后两位
print(np.round(arr, 2))

0.16
[0.64149397 0.47048506 0.48141244 0.34733352 0.87341826 0.57570775
 0.93516669 0.49675606 0.61172953 0.55167966]
8
float64
[0.64 0.47 0.48 0.35 0.87 0.58 0.94 0.5  0.61 0.55]


# 数组和数的计算

In [24]:
# [1, 2, 3] + 5   # 列表无法直接和整数相加

In [25]:
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)

t2 = t1.tolist()
print(t1 + 2)  # 数组可与整数相加
# print(t2+2) 不能对列表进行直接加整数操作
print("-" * 20)

print(t1 * 2)
print("-" * 20)

print(t1 / 2)

#无论多少维的ndarray都可以直接和一个常数进行运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# ndarray与ndarray的运算

In [26]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)

print(t1 + t2)
print('-' * 50)

print(t1 * t2)  # 非矩阵乘法，乃对应分量相乘

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [27]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(24).reshape((6, 4))
print(t1)
print(t2)
print(t1 - t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


ValueError: operands could not be broadcast together with shapes (4,6) (6,4) 

In [ ]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
t1 - t2

In [ ]:
(t1 - t2).shape

In [ ]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
t1 - t2

In [ ]:
#随机3维数组
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a)
print('*' * 50)
print(b)
a - b

结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1

# 练习轴

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)

print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)

print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)

print(np.sum(a))  # 全元素加总
print("-" * 20)

In [ ]:
a = np.arange(24).reshape((2, 3, 4))
print(a)
b = np.sum(a, axis=0)
print("-" * 20)
print(b)
print(b.shape)

c = np.sum(a, axis=1)
print("-" * 20)
print(c)
print(c.shape)

d = np.sum(a, axis=2)
print("-" * 20)
print(d)
print(d.shape)

# 7索引和切片

In [ ]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开

In [ ]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)

print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)

print(t1[1:])  # 取连续的多行
print('*' * 20)

print(t1[1:3, :])  # 取连续的多行
print('*' * 20)

print(t1[[0, 2, 3]])  # 取不连续的多行

In [ ]:
print(t1[[0, 2, 3]])  # 取不连续的多行
#看列表
t2 = np.arange(24).reshape(4, 6).tolist()
t2[[0, 2, 3]]  # list indices must be integers or slices, not list

In [ ]:
print(t1[:, 1])  # 取一列
print('*' * 20)

print(t1[:, 1:])  # 连续的多列
print('*' * 20)

print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)

print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)

print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]

t1[1:3, 1:4]  #取1-3行，1-4列,左闭右开

# 8数组修改值

In [ ]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# 修改某一行的值
# t[1,:]=0
#
# 修改某一列的值
# t[:,1]=0
#
# 修改连续多行
# t[1:3,:]=0
#
# 修改连续多列
# t[:,1:4]=0
#
# 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and &   # np.logical_or |
# np.logical_not ~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	    # 逻辑非
# print(t)
t = t.clip(10, 18)  # 将数组 t 中的所有小于 10 的值设置为 10，所有大于 18 的值设置为 18，而介于 10 和 18 之间的值保持不变。
print(id(t))  # 返回一个新的数组
t

In [ ]:
t = np.arange(24).reshape(4, 6)
print(t)
t < 10  # 小于10为True

In [ ]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

In [ ]:
# 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)

In [ ]:
score[result] = 100  # 把result位置改为100
score

# 9数据的添加，删除与去重

In [ ]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成ValueError。
'''
 append的参数{arr： 输 入 数 组     values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）                                             axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组
 当axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。}
'''
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))  #ndarray会被展平
print('\n')
print(a)
print('-' * 50)

In [ ]:
b = np.array([[7, 8, 9]])   # 2维
print(b.ndim)
print(b)
print('-' * 50)

In [ ]:
print('沿轴 0 添加元素：')  #往哪个轴添加，那个轴size就变大
b = np.array([[7, 8, 9]])
print(np.append(a, b, axis=0))
print('\n')
print(a)

print('沿轴 1 添加元素：')
c = [[5, 5, 5], [7, 8, 9]]
print(np.append(a, c, axis=1))
print(a)
print('-' * 50)

In [ ]:
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 1, [11, 22]))
print('-' * 50)

print(np.insert(a, 1, [11, 12], axis=0))  #那个轴插入，哪个轴size变大

print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴  0 广播：')
print(np.insert(a, 1, 11, axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, 1, [1, 2, 5], axis=1))

In [ ]:
# numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开'''
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a, 5))
print('\n')
print(a)    # a不会改变

print('删除第一行：')
print(np.delete(a, 1, axis=0))
print('\n')

print('删除第一列：')
print(np.delete(a, 1, axis=1))

In [ ]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展平
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储存
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储存
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

print('第一个数组：')
print(a)
print('\n')

# 去除重复元素，输出的是有序序列
# print ('第一个数组的去重值：')
# u = np.unique(a)
# print (u)
# print ('\n')

# print ('去重数组的索引数组：')
# u,indices = np.unique(a, return_index = True)
# print(u)
# print (indices)
# print ('\n')

# print ('我们可以看到每个和原数组下标对应的数值：')
# print ('去重数组的下标：')
# u,indices = np.unique(a,return_inverse = True)
# print (u)
# print (indices)
# print ('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u)
print(indices)
u

# numpy的计算（数学函数）

In [ ]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)

# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值，对应的轴就消失
result = np.max(score, axis=1)
print(result)

# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)

# 5. 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；



# 通用函数：
# numpy.sqrt(array)	平方根函数
# numpy.exp(array)	e^array[i]的数组
# numpy.abs/fabs(array)	计算绝对值
# numpy.square(array)	计算各元素的平方 等于array^2
# numpy.log/log10/log2(array)	计算各元素的各种对数
# numpy.sign(array)	计算各元素正负号
# numpy.isnan(array)	计算各元素是否为NaN
# numpy.isinf(array)	计算各元素是否为NaN
# numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
# numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
# numpy.ceil(array)	向上取整,也就是取比这个数大的整数
# numpy.floor(array)	向下取整,也就是取比这个数小的整数
# numpy.rint(array)	四舍五入
# numpy.trunc(array)	向0取整
# 
# numpy.add(array1,array2)	元素级加法
# numpy.subtract(array1,array2)	元素级减法
# numpy.multiply(array1,array2)	元素级乘法
# numpy.divide(array1,array2)	元素级除法 array1./array2
# numpy.power(array1,array2)	元素级指数 array1.^array2
# numpy.maximum/minimum(array1,aray2) 元素级最大值
# numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
# numpy.mod(array1,array2)	元素级求模
# numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
# numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)   元素级比较运算，产生布尔数组
# numpy.logical_end/logical_or/logic_xor(array1,array2)  元素级的真值逻辑运算

In [ ]:
# 6. 求平均值
result = np.mean(score)  # 获取所有数据的平均值
print(result)
result = np.mean(score, axis=0)  # 获取某一行或者某一列的平均值
print(result)

# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.cumsum(axis=0))

# [1, 2, 3]------>	|1	|2	|3	|
# [4, 5, 6]------>	|5=1+4 |7=2+5 |9=3+6|

print(arr.cumsum(axis=1))

# [1, 2, 3]------>	|1	|2+1	|3+2+1	|
# [4, 5, 6]------>	|4	|4+5	|4+5+6	|

# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

In [ ]:
# 8. argmin求最小值索引
result = np.argmin(score, axis=0)
res = np.min(score, axis=0)  #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result, res)

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score, axis=0)
print(result)

# 10. 极 值
result = np.ptp(score, axis=None)  #就是最大值和最小值的差
print(result)

In [ ]:
t = np.arange(30).reshape(10, 3)
print(t)
np.mean(t, axis=0)

# 数组的拼接

In [29]:
# 有的时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np

# 1. 根据轴连接的数组序列，concatenate没有改变数组的维度
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
# 要求a,b两个数组的维度相同

print('沿轴 0 连接两个数组：')
print(np.concatenate((a, b), axis=0))  #写哪个轴，哪个轴就变化
print('-' * 50)

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------------------------------------


In [30]:
print('沿轴 1 连接三个数组：')
print(np.concatenate((a, b,c), axis=1))

沿轴 1 连接三个数组：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [31]:
# 堆叠
print('-' * 50)
print(np.stack((a, b, c), axis=1))
print(np.stack((a, b,c), axis=1).shape)  #stack会增加维度
print('-' * 50)
print(np.stack((a, b, c), axis=0))
print(np.stack((a, b,c), axis=0).shape) 

--------------------------------------------------
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]
(2, 3, 2)
--------------------------------------------------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [32]:
# 2. 根据轴进行堆叠，2维会变为3维
arrays = [np.arange(12).reshape(3, 4) for _ in range(10)]
print(arrays)
print(len(arrays))

print('沿轴 0 连接两个数组：')
result0 = np.stack(arrays, axis=0)
print(result0.shape)  # (10,3,4)
print (result0)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
10
沿轴 0 连接两个数组：
(10, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [

In [34]:
print('-' * 50)
print('沿轴 1 连接两个数组：')
print(arrays[0])
result1 = np.stack(arrays, axis=1)
print(result1.shape)  #(3,10,4)
print(result1)

--------------------------------------------------
沿轴 1 连接两个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 10, 4)
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]]


In [35]:
print('-' * 50)
print('沿轴 2连接两个数组：这里-1和2是等价的')
result2 = np.stack(arrays, axis=-1)
print(arrays[0])
print(result2.shape)    # (3, 4, 10)
print(result2)

--------------------------------------------------
沿轴 2连接两个数组：这里-1和2是等价的
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4, 10)
[[[ 0  0  0  0  0  0  0  0  0  0]
  [ 1  1  1  1  1  1  1  1  1  1]
  [ 2  2  2  2  2  2  2  2  2  2]
  [ 3  3  3  3  3  3  3  3  3  3]]

 [[ 4  4  4  4  4  4  4  4  4  4]
  [ 5  5  5  5  5  5  5  5  5  5]
  [ 6  6  6  6  6  6  6  6  6  6]
  [ 7  7  7  7  7  7  7  7  7  7]]

 [[ 8  8  8  8  8  8  8  8  8  8]
  [ 9  9  9  9  9  9  9  9  9  9]
  [10 10 10 10 10 10 10 10 10 10]
  [11 11 11 11 11 11 11 11 11 11]]]


In [36]:
# 3. 矩阵垂直拼接，vstack没有增加维数，类似于concatenate 
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)

# 4. 矩阵水平拼接，类似于concatenate  horizontal
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.hstack((v1, v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


# 分割

In [37]:
# 1. 将一个数组分割为多个子数组
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
'''
import numpy as np

arr = np.arange(12).reshape(4, 3)
print(arr)
print('将数组分为三个大小相等的子数组：b是一个列表')
b = np.split(arr, 3, axis=1) #按那个轴，那个轴发生变化
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
将数组分为三个大小相等的子数组：b是一个列表
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [38]:
b[0].shape

(4, 1)

In [39]:
b = np.split(arr, 4, axis=0)
print(b)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [40]:
# numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
c = np.hsplit(arr, 3)
print(c)  #c是列表
print(c[0].shape)

[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
(4, 1)


In [41]:
d = np.random.random((2, 6))
# 形状为 (2, 6) 的二维数组 d，其元素是从 [0, 1) 区间均匀分布的随机数
print(d)

[[0.10535686 0.06704714 0.12175486 0.74146709 0.05582327 0.02504743]
 [0.38175646 0.39781621 0.49121962 0.35770105 0.50798696 0.1516724 ]]


In [44]:
# numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4, 4)

print('第一个数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
